version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/home/root/ws/src/test_callback_groups
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/root/.Xauthority:rw
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /home/root/ws
    command: /bin/bash